### ISSUE TITLE
Checking Admin Acess

### ISSUE THREAD

**Issue by henglonerai** [shamil-t/ehr-blockchain#11]
Good day to you sir. Currently, my issue will be given the pop out for checking admin access. I am not sure what is the issue here.

![image](https://user-images.githubusercontent.com/115034517/193892382-9755b4c3-3f23-45a7-8d1b-cde620a84c11.png)

**Comment by shamil-t** [comment]
make  sure you ran` truffle migrate`

and connect to metamask to first account from ganahe.

_**first account is the one who deploy the contract, and set as admin._

**Comment by shamil-t** [comment]
you can follow the steps in installing _(created for an older version)_
https://www.youtube.com/playlist?list=PL54V-i7zW55d1VKxEkp9DCPt5k_zE6m3X

**Comment by henglonerai** [comment]
thank you and i got it! fantastic job btw! also, im running to another problem where I am unable to add the doctor into the network. 

according to the video, it shows that after clicking on 'add doctor' it will load and pops out metamask notification of transaction fees. however for my side here, it only shows a pop up 'adding doctor to the network'. I use a difference ganache address as shown in the video but yet it does not work.

![image](https://user-images.githubusercontent.com/115034517/193898994-e07153df-0fa2-41aa-8450-91c9b3eda48a.png)

**Comment by shamil-t** [comment]
Infura gateway no longer work without project id.
you can either create an account or use IPFS locally.
refer this issue, 
https://github.com/shamil-t/ehr-blockchain/issues/10

**Comment by shamil-t** [comment]
updated the main branch, and resolved IPFS issue.
