### ISSUE TITLE
Not able to add patients

### ISSUE THREAD

**Issue by pranavsh1408** [shamil-t/ehr-blockchain#16]
![image](https://user-images.githubusercontent.com/82723340/206904859-00869026-770e-4771-bdc2-9195fc045bdc.png)

**Comment by nihalsalam77** [comment]
Try changing the Metamask user

**Comment by nihalsalam77** [comment]
> ![image](https://user-images.githubusercontent.com/82723340/206904859-00869026-770e-4771-bdc2-9195fc045bdc.png)


Try changing the Metamask user

**Comment by shamil-t** [comment]
Hi guys,

this is a sample version of of full project:https://youtu.be/d_-pWoGgdVs

for full project contact: tshamil90@gmail.com
