### ISSUE TITLE
Same doctor adding again and again in the view section

### ISSUE THREAD

**Issue by Dimplesingh442** [shamil-t/ehr-blockchain#17]
every time I'm adding any new doctor then all the other doctors which was previously added become the same as show in the ss below
<img width="1440" alt="Screenshot 2023-02-28 at 2 20 09 PM" src="https://user-images.githubusercontent.com/91384975/221802383-544519c9-e4bb-4019-89c9-e200a1a41662.png">

**Comment by shamil-t** [comment]
Hi @Dimplesingh442 

fixed the bug in the latest version

![image](https://user-images.githubusercontent.com/67453312/226015491-de32c3ad-cf91-4753-a254-ec186024ad47.png)

**Comment by Dimplesingh442** [comment]
thankyou so much
