### ISSUE TITLE
how can do it ubuntu server and windows client?

### ISSUE THREAD

**Issue by johnfelipe** [shamil-t/ehr-blockchain#2]
root@eh68221471013:~/ehr-blockchain# truffle migrate

	Compiling your contracts...
	===========================
	✔ Fetching solc version list from solc-bin. Attempt #1
	✔ Downloading compiler. Attempt #1.
	> Compiling ./src/contracts/Contract.sol
	> Compiling ./src/contracts/Migrations.sol
	> Compiling ./src/contracts/Roles.sol
	> Artifacts written to /root/ehr-blockchain/src/abis
	> Compiled successfully using:
	   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

	> Something went wrong while attempting to connect to the network at http://127.0.0.1:7545. Check your network configuration.

	Could not connect to your Ethereum client with the following parameters:
		- host       > 127.0.0.1
		- port       > 7545
		- network_id > 5777
	Please check that your Ethereum client:
		- is running
		- is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
		- is accessible over the network
		- is properly configured in your Truffle configuration file (truffle-config.js)

	Truffle v5.4.28 (core: 5.4.28)
	Node v10.19.0

pls help me to solve this

**Comment by shamil-t** [comment]
install ganache, and connect it. it should run in the background.

https://www.youtube.com/watch?v=B-38eKVahU0&list=PL54V-i7zW55d1VKxEkp9DCPt5k_zE6m3X

**Comment by johnfelipe** [comment]
Set up complete with cli
