### ISSUE TITLE
MetaMask notification is not coming after adding details of doctors

### ISSUE THREAD

**Issue by Shubhangi072** [shamil-t/ehr-blockchain#24]
![Screenshot (218)](https://user-images.githubusercontent.com/106398285/236397629-5fc57b08-7c5d-4f5e-97de-85d867198009.png)

**Comment by shamil-t** [comment]
Is Ganache running?

**Comment by shamil-t** [comment]
check IPFS installed and configured
refer to this: https://github.com/shamil-t/ehr-blockchain/issues/15

**Comment by Shubhangi072** [comment]
Yes my Ganache is running and I had done changes as per #15 but still its not working

**Comment by shamil-t** [comment]
Could you please send a screenshot of the browser console while you're facing the issue?

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/816bcd9a-bfee-4b57-ad75-e45f86685117)

Ganache is working

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/366c3535-e12d-4382-9a38-65b54188cedd)
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/76daa712-2b3e-4247-8d37-051bd18883ea)

Also done the changes

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/f2645642-1056-4246-bca0-76afac40021b)

Still its is not giving me notification on MetaMask

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/2e990354-281b-4f09-b82b-4660f9d06bc3)

What I have to do here?

**Comment by shamil-t** [comment]
please send a screenshot of the browser console (F12 key> console) while you're facing the issue.

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/3f356948-9e25-42ef-bdfd-ed9a64b5dc63)

**Comment by shamil-t** [comment]
have you restarted IPFS after configuring?

**Comment by Shubhangi072** [comment]
No, how can I do it ?

**Comment by shamil-t** [comment]
close IPFS and run: ipfs daemon

**Comment by Shubhangi072** [comment]
Yes sir, its working thank you so much

**Comment by Shubhangi072** [comment]
![Image](https://github.com/shamil-t/ehr-blockchain/assets/106398285/88ab6c8e-820c-40c6-b2ef-f04f87b07e6c)

Sir how can I work on this section?

**Comment by shamil-t** [comment]
for full project or modifications contact ***@***.***

**Comment by Doc-Groot09** [comment]
Hello.., I also facing the same issue. 
![Image](https://github.com/shamil-t/ehr-blockchain/assets/136812767/3bc0fc72-34cd-4fd3-b33e-f56bfb12308a)

But it doesn't giving me notification on MetaMask.
![Image](https://github.com/shamil-t/ehr-blockchain/assets/136812767/3d913b3e-4b2b-4e75-9d73-e53bc8950033)

Ganache is working and I done making changes in IPFS and restart it.
![Image](https://github.com/shamil-t/ehr-blockchain/assets/136812767/c0fca5e8-5cd9-47d0-839f-f594138dd68e)

Can you please help me to overcome this issue.. Waiting for your responds.
Thanking you...

**Comment by shamil-t** [comment]
make sure you are using only IPFS-CLI (kubo), not IPFS Desktop, if you installed IPFS Desktop stop it or uninstall it and delete the .ipfs folder in the above location, then configure IPFS.

**Comment by shamil-t** [comment]
the above-provided screenshot of the browser console didn't seem to be of this project.

**Comment by Doc-Groot09** [comment]
Thankyou for your reply and your time.

That was my mistake, I was using IPFS Desktop instead of IPFS-CLI (Kubo).
Now it's all clear and its working.

This project is amazing. How can I get the full project ??

Kindly please reply.

**Comment by Doc-Groot09** [comment]
Thankyou for your reply and your time.

That was my mistake, I was using IPFS Desktop instead of IPFS-CLI (Kubo). Now it's all clear and its working.

This project is amazing. How can I get the full project ??

Kindly please reply.
