### ISSUE TITLE
What is the cause of the problem?

### ISSUE THREAD

**Issue by Osam3** [shamil-t/ehr-blockchain#28]
@shamil-t  I followed the steps carefully, but when I run the project, I am directed to this. I cannot access the home page. What is the cause of the problem, please?
![1](https://github.com/shamil-t/ehr-blockchain/assets/100808992/e541cb95-ee03-449c-a6d4-453419b52490)
![2](https://github.com/shamil-t/ehr-blockchain/assets/100808992/983db1b2-994a-4e02-abc0-23ec69a2ec34)

**Comment by shamil-t** [comment]
please elaborate on the issue you are facing.

**Comment by Osam3** [comment]
![1](https://github.com/shamil-t/ehr-blockchain/assets/100808992/c04c7408-8f69-4af8-b220-2280e9ca95cd)
Note here that this page does not work for me on the home page. I mean, when you run the project, this page is supposed to appear, isn’t it like that or not?

**Comment by shamil-t** [comment]
have you run the truffle migrate command?

please make sure you followed all the steps mentioned in the [README](https://github.com/shamil-t/ehr-blockchain/blob/ehr-2.0/README.md)

EHR 2.0 demo : https://youtu.be/d_-pWoGgdVs

**Comment by Osam3** [comment]
I re-downloaded but the same problem, the home page does not appear
![Uploading EHR 2.0 - Google Chrome 1_13_2024 5_24_25 PM.png…]()

**Comment by shamil-t** [comment]
check the browser console for any errors

**Comment by Osam3** [comment]
![Uploading 6.jpg…]()

**Comment by Osam3** [comment]
I re-downloaded the program as it appears in the YouTube videos, but to no avail. Does ipfs affect or has an effect on this problem? I have downloaded ganache and metamask.

**Comment by Osam3** [comment]
![6](https://github.com/shamil-t/ehr-blockchain/assets/100808992/63fc7098-b645-4f74-ac46-052ebb87e1d4)
When pressed doctor

**Comment by Osam3** [comment]
![Uploading 6.jpg…]()

**Comment by shamil-t** [comment]
for the full project contact tshamil90@gmail.com
